# Project information
site_name: Material Desingn 开发者文档
site_description: 'Material Components for Android'
site_author: '脉脉不得语'
site_url: 'http://materialdoc.cn'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/materialdoccn/materialdoc-web'

# Copyright
copyright: 'Copyright &copy; 2017 - 2018 脉脉不得语'

# Documentation and theme
theme_dir: 'material'
site_favicon: 'images/favicon.ico'

# Options
extra:
  social:
    - type: 'github'
      link: 'https://github.com/materialdoccn'
    - type: 'twitter'
      link: 'https://twitter.com/inferjay'
    - type: 'weibo'
      link: 'https://weibo.com/innferjay'
  feature:
    tabs: true

# Extensions
markdown_extensions:
  - admonition
  - meta
  - codehilite
  - toc(permalink=true)

# Google Analytics
google_analytics:
  - 'UA-71100105-1'
  - 'auto'

pages:
    - Home:
      - 关于: index.md
      - 应用程序: application.md
      - 如何参与贡献: how-to-contribute.md
    - Components:
      - Auto-complete: components/autocomplete.md
      - Buttons: components/buttons.md
      - Buttons FAB: components/fab.md
      - Bottom navigation: components/bottom-navigation.md
      - Bottom sheets: components/bottom-sheets.md
      - Cards: components/cards.md
      - Dialogs: components/dialogs.md
      - Menus: components/menus.md
      - Pickers: components/pickers.md
      - Progress & activity: components/progress.md
      - Rating Bar: components/rating-bar.md
      - Selection controls: components/selection-controls.md
      - Snackbars & Toasts: components/snackbars-and-toasts.md
      - Tabs: components/tabs.md
      - Text fields: components/text-fields.md
      - Toolbars: components/toolbars.md
    - Patterns:
      - Data formats: patterns/data-formats.md
      - Launch screens: patterns/launch-screen.md
      - Navigation drawer: patterns/navigation-drawer.md
      - Notifications: patterns/notifications.md
      - Swipe to refresh: patterns/swipe-to-refresh.md
    # Pages which are not visible from menu
    - 'article-template.md'
